<?php

function expertaccess_views_api() {
  return array('api' => 3.0);
}

function expertaccess_views_default_views() {
  civicrm_initialize();
  $files = file_scan_directory(drupal_get_path('module', 'expertaccess'). '/views', '/.inc/');
  foreach ($files as $filepath => $file) {
    try {
      require $filepath;
      if (isset($view)) {
        $views[$view->name] = $view;
      }
    } catch (Exception $e) {
      //do nothing
    }
  }
  return $views;
}

function expertaccess_get_role_ids($roles) {
  $rids = array();
  $available_roles = user_roles();
  foreach($roles as $role) {
    $rid = array_search($role, $available_roles);
    if ($rid !== false) {
      $rids[$rid] = $rid;
    }
  }
  
  return $rids;
}
